sudo: false
language: generic
os: osx
before_install:
  # use pyenv to install python 3.5.1
  - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install 3.5.1
  - pyenv global 3.5.1
  - pyenv rehash
  - python -m pip install --user --upgrade pip virtualenv
  # create virtual environment
  - python -m virtualenv .env
  - source .env/bin/activate
  - python --version
  # install requirements
  - pip install pyqt5 flake8 pytest
  - python -c "import sip; print(sip.__file__); print('sip version:', sip.SIP_VERSION_STR)"
  - python -c "from PyQt5 import Qt; print(Qt.__file__); print('PyQt5 version:', Qt.PYQT_VERSION_STR)"
  - pip install -r requirements.txt
install:
  - pip install -v .
script:
  - flake8 --config=setup.cfg Lib/trufont
  - py.test -v -r a tests/
